name: build

on:
  push:
    branches:
      - master
    tags:
      - '*.*.*'
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - name: Build, tag and push the Docker image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

          docker build --tag ghcr.io/tgagor/owasp-dependency-check --cache-from ghcr.io/tgagor/owasp-dependency-check .

          docker run -i --rm ghcr.io/tgagor/owasp-dependency-check -version

          docker tag ghcr.io/tgagor/owasp-dependency-check ghcr.io/tgagor/owasp-dependency-check:${GITHUB_REF##*/}
          docker tag ghcr.io/tgagor/owasp-dependency-check ghcr.io/tgagor/owasp-dependency-check:${{ github.sha }}

          docker push ghcr.io/tgagor/owasp-dependency-check
          docker push ghcr.io/tgagor/owasp-dependency-check:${{ github.sha }}
          docker push ghcr.io/tgagor/owasp-dependency-check:${GITHUB_REF##*/}

  security-scan:
    runs-on: ubuntu-20.04
    needs:
      - build
    steps:
      - uses: actions/checkout@v2
      - name: Fetch image
        run: |
          echo ${{ secrets.CR_PAT }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/tgagor/owasp-dependency-check:${{ github.sha }}

      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@master
        with:
          image-ref: ghcr.io/tgagor/owasp-dependency-check:${{ github.sha }}
          format: template
          template: '@/contrib/sarif.tpl'
          exit-code: 0
          output: trivy-results.sarif

      - name: Upload Trivy scan results to GitHub Security tab
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: trivy-results.sarif
